### ISSUE TITLE
Keras 2 Warnings

### ISSUE THREAD

**Issue by anjabeth** [nadbordrozd/neural_playground#2]
When running train_text_gen.py, I get the following warnings, which I'm not totally sure how to fix: 

 The semantics of the Keras 2 argument  `steps_per_epoch` is not the same as the Keras 1 argument `samples_per_epoch`. `steps_per_epoch` is the number of batches to draw from the generator at each epoch. Update your method calls accordingly.

Update your `fit_generator` call to the Keras 2 API: `fit_generator(<generator..., validation_data=<generator..., steps_per_epoch=791004, epochs=1, validation_steps=86927)`

The warnings are being triggered by this part, I think: `
 `samples_per_epoch=samples, nb_epoch=1)`

I'm just starting out with Keras, so don't know enough to fix these calls - do you know what the best thing to do would be?

**Comment by nadbor-aimia** [comment]
Yeah, semantics of fit_generator changed with Keras 2 API. Fixed.

**Comment by anjabeth** [comment]
Thanks!
