### ISSUE TITLE
Is there a built-in way to generate output from older versions of the model?

### ISSUE THREAD

**Issue by anjabeth** [nadbordrozd/neural_playground#3]
Basically, I just want to see how the generated text improves over the course of training without babysitting the command line output. I can always change the code to write the output to file, but didn't know if there was built-in access to earlier "forms" of the model or not.

**Comment by nadbor-aimia** [comment]
There totally is! The model is saved after every epoch in directories like `model_dir/epoch_00001` etc. 
Running 
```bash
./generate_text.py \
    --model_path models/flat_earth_1 \
    --load_latest
    ...
```
will take the latest available epoch from `models/flat_earth_1` directory, but you can directly pick which epoch you want by running without the `--load_latest` flag:
```bash
./generate_text.py \
    --model_path models/flat_earth_1/epoch_00017
   ...
```
\- as explained in the doc - which you can display by running `generate_text.py --help`

**Comment by anjabeth** [comment]
Perfect, thanks so much! I thought there was a way to do it, but couldn't rememer exactly how.
